title: Virage
views: 
  - cards:
      - type: custom:vertical-stack-in-card
        title: Virage Devices on Your System
        cards:
          - type: markdown
            content: Click on a device to access it's Home Assistant settings.  Click <ha-icon icon="mdi:open-in-new"> </ha-icon> to open a device's Admin Interface.
          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              title: Switches
              show_header_toggle: false
              state_color: true
            filter:
              include:
                - domain: switch
                  attributes:
                    Manufacturer: VirageLabs
                    Model: VirageSwitch
                  options:
                    type: 'custom:config-template-card'
                    variables:
                      - 'states[''this.entity_id''].attributes.URL'
                      - 'states[''this.entity_id''].attributes.Wifi.SSId'
                      - 'states[''this.entity_id''].attributes.Wifi.RSSI'
                    entities:
                      - this.entity_id
                    card:
                      type: entities
                      entities:
                        - entity: this.entity_id
                          state_color: true
                          hold_action:
                            action: url
                            url_path: '${vars[0]}'
                        - type: custom:ext-weblink
                          name: '${"WiFi: " + vars[1] + " - Signal "+ vars[2] + "%"}'
                          url: '${vars[0]}'
                          icon: mdi:wifi

          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              title: Outlets
              show_header_toggle: false
            filter:
              include:
                - domain: switch
                  attributes:
                    Manufacturer: VirageLabs
                    Model: ViragePlug
                  options:
                    type: 'custom:config-template-card'
                    variables:
                      - 'states[''this.entity_id''].attributes.URL'
                      - 'states[''this.entity_id''].attributes.Wifi.SSId'
                      - 'states[''this.entity_id''].attributes.Wifi.RSSI'
                    entities:
                      - this.entity_id
                    card:
                      type: entities
                      entities:
                        - entity: this.entity_id
                          state_color: true
                          hold_action:
                            action: url
                            url_path: '${vars[0]}'
                        - type: custom:ext-weblink
                          name: '${"WiFi: " + vars[1] + " - Signal "+ vars[2] + "%"}'
                          url: '${vars[0]}'
                          icon: mdi:wifi



          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              title: Dimmers
              show_header_toggle: false
              icon: hass:lightbulb
            filter:
              include:
                - domain: light
                  attributes:
                    Manufacturer: VirageLabs
                    Model: VirageDimmer
                  options:
                    type: 'custom:config-template-card'
                    variables:
                      - 'states[''this.entity_id''].attributes.URL'
                      - 'states[''this.entity_id''].attributes.Wifi.SSId'
                      - 'states[''this.entity_id''].attributes.Wifi.RSSI'
                    entities:
                      - this.entity_id
                    card:
                      type: entities
                      entities:
                        - entity: this.entity_id
                          state_color: true
                          hold_action:
                            action: url
                            url_path: '${vars[0]}'
                        - type: custom:ext-weblink
                          name: '${"WiFi: " + vars[1] + " - Signal "+ vars[2] + "%"}'
                          url: '${vars[0]}'
                          icon: mdi:wifi
 
          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              title: RF Bridges
              show_header_toggle: false
            filter:
              include:
                - domain: sensor
                  attributes:
                    Manufacturer: VirageLabs
                    Model: VirageBridge
                  options:
                    type: 'custom:config-template-card'
                    variables:
                      - 'states[''this.entity_id''].attributes.URL'
                      - 'states[''this.entity_id''].attributes.Wifi.SSId'
                      - 'states[''this.entity_id''].attributes.Wifi.RSSI'
                    entities:
                      - this.entity_id
                    card:
                      type: entities
                      entities:
                        - entity: this.entity_id
                          hold_action:
                            action: url
                            url_path: '${vars[0]}'
                        - type: custom:ext-weblink
                          name: '${"WiFi: " + vars[1] + " - Signal "+ vars[2] + "%"}'
                          url: '${vars[0]}'
                          icon: mdi:wifi

          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              title: Door & Window Contacts
              show_header_toggle: false
            filter:
              exclude:
                - name: "Door/Window State*"
                  domain: binary_sensor
                - name: "Door/Window Battery*"
                  domain: binary_sensor
              include:
                - domain: binary_sensor
                  attributes:
                    device:manufacturer: VirageLabs
                    device:model: Door/Window Sensor

          - type: custom:auto-entities
            show_empty: false
            card:
              type: entities
              title: Motion Sensors
              show_header_toggle: false
            filter:
              exclude:
                - name: "Motion State*"
                  domain: binary_sensor
                - name: "Motion Battery*"
                  domain: binary_sensor
              include:
                - domain: binary_sensor
                  attributes:
                    device:manufacturer: VirageLabs
                    device:model: Motion Sensor

      - type: vertical-stack
        title: Add Door Contacts or Motion Sensors
        cards:
          - type: markdown
            content: Turn Discovery on, then trigger the sensor or contact.<p>
          - type: entities
            entities:
              - entity: automation.door_contact_motion_sensor_setup
                icon: mdi:magnify-plus
                name: "Enable Discovery"
                tap_action:
                  action: none
          - type: custom:auto-entities
            card:
              type: glance
            filter:
              include:
                - name: "Motion *"
                  domain: binary_sensor
                - name: "Door/Window *"
                  domain: binary_sensor
          - type: markdown
            content: Icons for newly discovered items will be displayed above.  Click on the icon to open the properties dialog, then the <ha-icon icon="mdi:cog"> </ha-icon>
                     in the top right corner to update the name and/or icon of the item.<p>
                     Discovery will turn off automatically once something is discovered.


    title: Devices
