blueprint:
  name: Four Way Switch
  description: 'Create a Virtual 4-Way Switch'
  domain: automation
  input:
    entity_1:
      name: First Light/Switch
      selector:
        entity:
    entity_2:
      name: Second Light/Switch
      selector:
        entity:
    entity_3:
      name: Third Light/Switch
      selector:
        entity:

mode: single
max_exceeded: silent
variables:
  entity_1: !input 'entity_1'
  entity_2: !input 'entity_2'
  entity_3: !input 'entity_3'
trigger:
- entity_id: &id003
  - !input 'entity_1'
  - !input 'entity_2'
  - !input 'entity_3'
  platform: state
  to:
  - 'on'
  - 'off'
action:
- service_template: homeassistant.turn_{{trigger.to_state.state}}
  data:
    entity_id: *id003
- delay:
    milliseconds: 500