blueprint:
  name: Door Contact & Motion Sensor Data Listener
  description: Monitor a 433 MHz sensor
  domain: automation
  input: {}
  source_url: https://raw.githubusercontent.com/brandondb1/blueprints/main/sensor_data.yaml
trigger:
- platform: mqtt
  topic: tele/rfbridge/RESULT
condition:
  condition: and
  conditions:
  - condition: template
    value_template: '{{trigger.payload_json.RfReceived.Sync | int > 12000 }}'
  - condition: template
    value_template: '{{trigger.payload_json.RfReceived.Sync | int < 15000 }}'
  - condition: or
    conditions:
    - condition: template
      value_template: '{{trigger.payload_json.RfReceived.Data[-1] == "E" }}'
    - condition: template
      value_template: '{{trigger.payload_json.RfReceived.Data[-1] == "B" }}'
    - condition: template
      value_template: '{{trigger.payload_json.RfReceived.Data[-1] == "6" }}'
    - condition: template
      value_template: '{{trigger.payload_json.RfReceived.Data[-1] == "A" }}'
action:
- choose:
  - conditions:
    - condition: and
      conditions:
      - condition: template
        value_template: '{{trigger.payload_json.RfReceived.Sync | int < 13801 }}'
      - condition: template
        value_template: '{{trigger.payload_json.RfReceived.Sync | int > 12000 }}'
      - condition: or
        conditions:
        - condition: template
          value_template: '{{trigger.payload_json.RfReceived.Data[-1] == "E" }}'
        - condition: template
          value_template: '{{trigger.payload_json.RfReceived.Data[-1] == "B" }}'
        - condition: template
          value_template: '{{trigger.payload_json.RfReceived.Data[-1] == "6" }}'
    sequence:
    - service: mqtt.publish
      data_template:
        topic: '{{ trigger.payload_json.RfReceived.Data[:5] + ''/tele/MOTION_STATE''
          }}'
        payload: "\n{% if trigger.payload_json.RfReceived.Data[-1] == \"B\" %}\n \
          \ ON\n{% elif trigger.payload_json.RfReceived.Data[-1] == \"E\" %}\n  ON\n\
          {% endif %}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: '{{ trigger.payload_json.RfReceived.Data[:5] + ''/tele/BATT_STATE''
          }}'
        payload: "\n{% if trigger.payload_json.RfReceived.Data[-1] == \"6\" %}\n \
          \ ON\n{% else %}\n  OFF\n{% endif %}"
        retain: true
  - conditions:
    - condition: and
      conditions:
      - condition: template
        value_template: '{{trigger.payload_json.RfReceived.Sync | int > 13800 }}'
      - condition: or
        conditions:
        - condition: template
          value_template: '{{trigger.payload_json.RfReceived.Data[-1] == "A" }}'
        - condition: template
          value_template: '{{trigger.payload_json.RfReceived.Data[-1] == "E" }}'
        - condition: template
          value_template: '{{trigger.payload_json.RfReceived.Data[-1] == "6" }}'
    sequence:
    - service: mqtt.publish
      data_template:
        topic: '{{ trigger.payload_json.RfReceived.Data[:5] + ''/tele/DOOR_STATE''
          }}'
        payload: "\n{% if trigger.payload_json.RfReceived.Data[-1] == \"A\" %}\n \
          \ ON\n{% elif trigger.payload_json.RfReceived.Data[-1] == \"E\" %}\n  OFF\n\
          {% endif %}"
        retain: true
    - service: mqtt.publish
      data_template:
        topic: '{{ trigger.payload_json.RfReceived.Data[:5] + ''/tele/BATT_STATE''
          }}'
        payload: "\n{% if trigger.payload_json.RfReceived.Data[-1] == \"6\" %}\n \
          \ ON\n{% else %}\n  OFF\n{% endif %}"
        retain: true
